[[language]]
name = "javascript"
auto-format = true
formatter = { command = 'prettier', args = [
  "--parser", "typescript",
  "--options-line-width", "100",
  "--config-precedence", "file-override", # Let these prefs be overridden by project-specific config files
] }

[[language]]
name = "typescript"
auto-format = true
formatter = { command = 'prettier', args = [
  "--parser", "typescript",
  "--options-line-width", "100",
  "--config-precedence", "file-override", # Let these prefs be overridden by project-specific config files
] }
