[[language]]
name = "javascript"
auto-format = true
formatter = { command = 'deno', args = ["fmt", "-", "--ext", "js", "--options-line-width", "100" ] }

[[language]]
name = "typescript"
auto-format = true
formatter = { command = 'deno', args = ["fmt", "-", "--ext", "ts", "--options-line-width", "100" ] }
